Repository hmcts/chart-java, pull requests merged in 2019-09, with the labels that each got.

#61 Adding templating for ingress
  README.md
  ci-values.yaml
  java/Chart.yaml
  java/templates/ingress.yaml
Labels: enhancement

#62 Bumping to latest postgresql chart
  java/Chart.yaml
  java/requirements.yaml
  java/values.yaml
Labels: dependencies

#66 Remove resource group and subscription ID
  README.md
  ci-values.yaml
  java/Chart.yaml
  java/templates/deployment.yaml
Labels: chore
